// Spill Lab v4.1 approximate room-noise observer.
// Microphone audio terminates at zero gain and never enters the demo mix.

const UPDATE_MS=100, NUMERIC_UPDATE_MS=1000, DISPLAY_MIN_DB=30, DISPLAY_MAX_DB=100, OFFICE_REFERENCE_DB_A=50;
const MIN_HOLD_MS=1000, STORAGE_KEY='spill-room-meter-calibration-v1';
let activeInstance=null,fallbackAudioContext=null;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const dbFromRms=b=>{let s=0;for(const x of b)s+=x*x;return s>1e-16?10*Math.log10(s/b.length):-100;};
const powerMeanDb=values=>{const good=values.filter(Number.isFinite);return good.length?10*Math.log10(good.reduce((s,v)=>s+Math.pow(10,v/10),0)/good.length):null;};
const meterWidth=db=>clamp((db-DISPLAY_MIN_DB)/(DISPLAY_MAX_DB-DISPLAY_MIN_DB)*100,0,100);
const roundToSix=v=>Math.round(v/6)*6;
const onOff=v=>v===true?'on':v===false?'off':'?';
function getFallbackAudioContext(){if(!fallbackAudioContext){const C=window.AudioContext||window.webkitAudioContext;if(!C)throw new Error('Web Audio unavailable.');fallbackAudioContext=new C();}return fallbackAudioContext;}
function fallbackDemoPlaying(){const b=document.getElementById('startBoth');return!!b&&/pause/i.test(b.textContent||'');}
function loadSavedCalibration(){try{const s=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');return s&&Number.isFinite(s.offsetDb)?s:null;}catch{return null;}}
function saveCalibration(data){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(data));}catch{}}
function ageText(ts){if(!Number.isFinite(ts))return 'previous calibration';const s=Math.max(0,(Date.now()-ts)/1000);if(s<90)return 'just now';const m=Math.floor(s/60);if(m<60)return `${m} min ago`;const h=Math.floor(m/60);if(h<48)return `${h} h ago`;return `${Math.floor(h/24)} d ago`;}

export function createRoomMeter({getAudioContext=getFallbackAudioContext,isDemoPlaying=fallbackDemoPlaying}={}){
 if(activeInstance)return activeInstance;const panel=document.getElementById('roomMeterPanel');if(!panel)return{stop(){}};
 Object.assign(panel.style,{background:'linear-gradient(180deg,#10252a 0%,#0f1d22 100%)',borderColor:'#3a8a91',boxShadow:'0 0 0 1px rgba(75,160,168,.16) inset'});
 const startButton=panel.querySelector('#roomMeterStart'),stopButton=panel.querySelector('#roomMeterStop'),status=panel.querySelector('#roomMeterStatus'),fullValue=panel.querySelector('#roomMeterFullValue'),aValue=panel.querySelector('#roomMeterAValue'),peakValues=panel.querySelector('#roomMeterPeakValues'),suggestion=panel.querySelector('#roomMeterSuggestion'),fullFill=panel.querySelector('#roomMeterFullFill'),aFill=panel.querySelector('#roomMeterAFill');
 const row=startButton.parentElement;
 const c05=document.createElement('button'),c025=document.createElement('button'),manual=document.createElement('button'),spl=document.createElement('input');
 c05.type=c025.type=manual.type='button';c05.textContent='HOLD voice 0.5 m · 63 dBA';c025.textContent='HOLD voice 0.25 m · 69 dBA';manual.textContent='Use external SPL reference';
 for(const b of[c05,c025,manual])b.disabled=true;row?.append(c05,c025);
 const details=document.createElement('details');details.style.marginTop='10px';const summary=document.createElement('summary');summary.textContent='Details · external SPL calibration and microphone state';summary.style.cursor='pointer';summary.style.fontWeight='700';details.append(summary);const manualBox=document.createElement('div');Object.assign(manualBox.style,{marginTop:'10px',padding:'10px',border:'1px solid rgba(120,200,205,.35)',borderRadius:'8px',background:'rgba(5,20,24,.45)'});
 const manualTitle=document.createElement('div');manualTitle.textContent='External SPL meter calibration';Object.assign(manualTitle.style,{fontWeight:'700',marginBottom:'7px'});
 const manualControls=document.createElement('div');Object.assign(manualControls.style,{display:'flex',alignItems:'center',gap:'7px',flexWrap:'wrap'});
 const presets=[60,65,70,75,80].map(v=>{const b=document.createElement('button');b.type='button';b.textContent=`${v} dBA`;b.disabled=true;b.style.padding='6px 9px';b.addEventListener('click',()=>{spl.value=String(v);});return b;});
 spl.type='number';spl.min='40';spl.max='90';spl.step='1';spl.value='70';spl.title='External A-weighted SPL meter reading';Object.assign(spl.style,{width:'5.5em',padding:'7px 8px',background:'#102126',color:'#eef',border:'1px solid #4c7479',borderRadius:'7px'});
 const unit=document.createElement('span');unit.textContent='dBA';unit.style.opacity='.8';manualControls.append(...presets,spl,unit,manual);manualBox.append(manualTitle,manualControls);const technical=document.createElement('div');technical.textContent='Microphone state appears after start.';Object.assign(technical.style,{marginTop:'9px',fontSize:'12px',opacity:'.72'});details.append(manualBox,technical);
 const uiHost=status?.parentElement||panel;
 if(status&&status.parentElement===uiHost)uiHost.append(details);else uiHost.append(manualBox);
 const calBadge=document.createElement('div');Object.assign(calBadge.style,{marginTop:'10px',padding:'8px 10px',fontWeight:'700',fontSize:'13px',borderRadius:'6px',background:'rgba(80,170,180,.18)',border:'1px solid rgba(90,180,190,.35)'});
 const indicator=document.createElement('div');indicator.textContent='VOICE REFERENCE IDLE';Object.assign(indicator.style,{marginTop:'8px',padding:'6px 10px',fontWeight:'700',fontSize:'13px',textAlign:'left',borderRadius:'6px',background:'rgba(120,120,120,.18)'});
 if(status&&status.parentElement===uiHost){uiHost.insertBefore(calBadge,status);uiHost.insertBefore(indicator,status);}else{uiHost.append(calBadge,indicator);}
 let stream=null,source=null,fullAnalyser=null,aAnalyser=null,silentSink=null,timer=null,mode='idle',trackSettingsText='',calibrationOffset=null,voiceReferenceRaw=null,calibrationInfo=null,holdSamples=[],holdStarted=0,holdTarget=null,holdDistance='',holdBackgroundRaw=null,recentA=[],recentFull=[],recentFullPeak=[],recentAPeak=[],smoothFull=null,smoothA=null,peakHeldFull=null,peakHeldA=null,lastPeakAt=0,lastNumericAt=0;
 const addPeakMarker=fill=>{const track=fill?.parentElement;if(!track)return null;track.style.position='relative';const marker=document.createElement('div');Object.assign(marker.style,{position:'absolute',top:'0',bottom:'0',width:'2px',background:'#fff',boxShadow:'0 0 4px rgba(255,255,255,.85)',left:'0%',pointerEvents:'none'});track.append(marker);return marker;};
 const fullPeakMarker=addPeakMarker(fullFill),aPeakMarker=addPeakMarker(aFill);
 const addScale=fill=>{const track=fill?.parentElement;if(!track)return;const scale=document.createElement('div');Object.assign(scale.style,{position:'relative',height:'13px',fontSize:'10px',lineHeight:'1',opacity:'.62',marginTop:'4px'});for(let db=30;db<=100;db+=10){const tick=document.createElement('span');tick.textContent=db;Object.assign(tick.style,{position:'absolute',left:`${meterWidth(db)}%`,transform:db===30?'none':db===100?'translateX(-100%)':'translateX(-50%)'});scale.append(tick);}track.insertAdjacentElement('afterend',scale);};addScale(fullFill);
 const saved=loadSavedCalibration();if(saved){calibrationOffset=saved.offsetDb;voiceReferenceRaw=saved.voiceRawDbfs??null;calibrationInfo={...saved,loaded:true};}
 function renderCalibrationState(info=calibrationInfo){if(!info||!Number.isFinite(calibrationOffset)){calBadge.textContent='CALIBRATION: none · meter is showing raw microphone level';calBadge.style.background='rgba(180,130,70,.18)';return;}let text='';if(info.method==='voice'){const distance=info.targetDbA===69?'0.25 m':'0.5 m';text=`CALIBRATION IN USE: ${info.loaded?'saved ':' '}voice ${distance} · ${Number(info.targetDbA).toFixed(0)} dBA · offset ${calibrationOffset>=0?'+':''}${calibrationOffset.toFixed(1)} dB · ${ageText(info.savedAt)}`;}else if(info.method==='external-spl'){text=`CALIBRATION IN USE: ${info.loaded?'saved ':''}external SPL · ${Number(info.targetDbA).toFixed(0)} dBA · offset ${calibrationOffset>=0?'+':''}${calibrationOffset.toFixed(1)} dB · ${ageText(info.savedAt)}`;}else{text=`CALIBRATION IN USE: saved legacy calibration · offset ${calibrationOffset>=0?'+':''}${calibrationOffset.toFixed(1)} dB`;}
 calBadge.textContent=text.replace(/\s+/g,' ').trim();calBadge.style.background=info.loaded?'rgba(80,140,185,.23)':'rgba(70,180,100,.24)';}
 renderCalibrationState();
 // EN: Calibrated SPL brightness is presentation only; it does not modify microphone measurement.
 function splFillColour(db){
   if(!Number.isFinite(db))return '#3b5558';
   if(db<60)return '#244946';
   if(db<70){const t=(db-60)/10;return `rgb(${Math.round(36+18*t)},${Math.round(73+118*t)},${Math.round(70+96*t)})`;}
   if(db<80){const t=(db-70)/10;return `rgb(${Math.round(54+188*t)},${Math.round(191+60*t)},${Math.round(166+72*t)})`;}
   return '#f4fffb';
 }
 function renderBars(raw){const est=calibrationOffset===null?null:{full:raw.full+calibrationOffset,a:raw.a+calibrationOffset};if(Number.isFinite(raw.full)){fullFill.style.width=`${meterWidth(est?est.full:raw.full)}%`;fullFill.style.background=splFillColour(est?.full);}if(Number.isFinite(raw.a)){aFill.style.width=`${meterWidth(est?est.a:raw.a)}%`;aFill.style.background=splFillColour(est?.a);}}
 function renderPeakMarkers(raw){const est=calibrationOffset===null?null:{full:raw.full+calibrationOffset,a:raw.a+calibrationOffset};if(fullPeakMarker&&Number.isFinite(raw.full))fullPeakMarker.style.left=`${meterWidth(est?est.full:raw.full)}%`;if(aPeakMarker&&Number.isFinite(raw.a))aPeakMarker.style.left=`${meterWidth(est?est.a:raw.a)}%`;if(peakValues&&Number.isFinite(raw.full)&&Number.isFinite(raw.a)){const f=est?est.full:raw.full,a=est?est.a:raw.a;peakValues.textContent=est?`Peak(A) ${a.toFixed(1)} dB(A) · Peak(C) ${f.toFixed(1)} dB`:`Peak(A) ${a.toFixed(1)} · Peak(C) ${f.toFixed(1)} dBFS`;}}
 function renderNumbers(raw){const est=calibrationOffset===null?null:{full:raw.full+calibrationOffset,a:raw.a+calibrationOffset};if(Number.isFinite(raw.full))fullValue.textContent=est?`C / full band ${est.full.toFixed(1)} dB`:`C / full band ${raw.full.toFixed(1)} dBFS raw`;if(Number.isFinite(raw.a))aValue.textContent=est?`${est.a.toFixed(1)} dB(A)`:`${raw.a.toFixed(1)} dBFS raw · A filter`;if(est&&Number.isFinite(est.a)){const relative=roundToSix(est.a-OFFICE_REFERENCE_DB_A),masterDb=clamp(-12+relative,-18,0),profile=masterDb===-18?'Quiet':masterDb===-12?'Office':masterDb===-6?'Noisy':'Fair / loud';suggestion.textContent=`Suggested HW master simulation: ${profile} · ${masterDb.toFixed(0)} dB · manual selection only`; }else suggestion.textContent='Use a held voice reference or an external A-weighted SPL meter.';}
 function backgroundRaw(){const cut=performance.now()-1200;return powerMeanDb(recentA.filter(x=>x.t>=cut).map(x=>x.db));}
 function beginHold(target,distance,e){e?.preventDefault();if(!stream||!aAnalyser)return;if(isDemoPlaying()){status.textContent='Stop demo playback before calibration.';return;}const bg=backgroundRaw();if(!Number.isFinite(bg)){status.textContent='Wait about 1 second for the room background, then hold the voice reference.';return;}holdSamples=[];holdStarted=performance.now();holdTarget=target;holdDistance=distance;holdBackgroundRaw=bg;mode='holding';indicator.textContent='MEASURING VOICE… HOLD';Object.assign(indicator.style,{padding:'12px',fontWeight:'800',fontSize:'18px',textAlign:'center',background:'rgba(255,170,0,.55)'});}
 function endHold(e){e?.preventDefault();if(mode!=='holding')return;const duration=performance.now()-holdStarted,voice=powerMeanDb(holdSamples),bg=holdBackgroundRaw;Object.assign(indicator.style,{padding:'6px 10px',fontWeight:'700',fontSize:'13px',textAlign:'left',background:'rgba(120,120,120,.18)'});if(duration<MIN_HOLD_MS||!Number.isFinite(voice)){indicator.textContent='HOLD AT LEAST 1 SECOND';status.textContent='Voice reference not accepted.';mode=calibrationOffset===null?'live-relative':'live';return;}const delta=Number.isFinite(bg)?voice-bg:null;if(!Number.isFinite(delta)||delta<6){indicator.textContent=`VOICE ONLY +${Number.isFinite(delta)?delta.toFixed(1):'?'} dB · NOT ACCEPTED`;status.textContent=holdTarget===63?'Background too loud. Try 0.25 m / 69 dBA or external SPL reference.':'Background too loud. Use external SPL reference or saved calibration.';mode=calibrationOffset===null?'live-relative':'live';return;}voiceReferenceRaw=voice;calibrationOffset=holdTarget-voice;calibrationInfo={offsetDb:calibrationOffset,voiceRawDbfs:voice,targetDbA:holdTarget,voiceOverBackgroundDb:delta,backgroundRawDbfs:bg,method:'voice',savedAt:Date.now(),loaded:false};saveCalibration(calibrationInfo);renderCalibrationState();indicator.textContent=`VOICE +${delta.toFixed(1)} dB · ACCEPTED`;indicator.style.background='rgba(70,180,100,.38)';status.textContent=`Voice ${holdDistance} accepted · raw ${voice.toFixed(1)} dBFS · background ${bg.toFixed(1)} dBFS · offset ${calibrationOffset>=0?'+':''}${calibrationOffset.toFixed(1)} dB`;mode='live';}
 function setExternal(){if(!stream||!aAnalyser)return;const target=Number(spl.value),raw=powerMeanDb(recentA.filter(x=>x.t>=performance.now()-1000).map(x=>x.db));if(!Number.isFinite(target)||target<40||target>90||!Number.isFinite(raw)){status.textContent='Enter external SPL meter reading 40–90 dBA and wait 1 second.';return;}calibrationOffset=target-raw;voiceReferenceRaw=null;calibrationInfo={offsetDb:calibrationOffset,targetDbA:target,rawDbfs:raw,method:'external-spl',savedAt:Date.now(),loaded:false};saveCalibration(calibrationInfo);renderCalibrationState();mode='live';indicator.textContent=`EXTERNAL SPL REF · ${target.toFixed(0)} dBA`;indicator.style.background='rgba(70,180,100,.38)';status.textContent=`External SPL calibration · browser raw ${raw.toFixed(1)} dBFS · offset ${calibrationOffset>=0?'+':''}${calibrationOffset.toFixed(1)} dB`;}
 function setTechnicalDetails(rawA){technical.textContent=`Raw A ${rawA.toFixed(1)} dBFS${trackSettingsText}`;}
 function tick(){if(!fullAnalyser||!aAnalyser)return;const f=new Float32Array(fullAnalyser.fftSize),a=new Float32Array(aAnalyser.fftSize);fullAnalyser.getFloatTimeDomainData(f);aAnalyser.getFloatTimeDomainData(a);const fr=dbFromRms(f),ar=dbFromRms(a),fp=20*Math.log10(Math.max(1e-8,...f.map(Math.abs))),ap=20*Math.log10(Math.max(1e-8,...a.map(Math.abs))),now=performance.now();recentA.push({t:now,db:ar});recentFull.push({t:now,db:fr});recentFullPeak.push({t:now,db:fp});recentAPeak.push({t:now,db:ap});while(recentA.length&&recentA[0].t<now-4000)recentA.shift();while(recentFull.length&&recentFull[0].t<now-4000)recentFull.shift();while(recentFullPeak.length&&recentFullPeak[0].t<now-1000)recentFullPeak.shift();while(recentAPeak.length&&recentAPeak[0].t<now-1000)recentAPeak.shift();smoothFull=smoothFull===null?fr:.22*fr+.78*smoothFull;smoothA=smoothA===null?ar:.22*ar+.78*smoothA;renderBars({full:smoothFull,a:smoothA});const elapsed=lastPeakAt?Math.max(0,(now-lastPeakAt)/1000):0,lastFull=Math.max(...recentFullPeak.map(x=>x.db)),lastA=Math.max(...recentAPeak.map(x=>x.db));peakHeldFull=peakHeldFull===null?lastFull:Math.max(lastFull,peakHeldFull-8*elapsed);peakHeldA=peakHeldA===null?lastA:Math.max(lastA,peakHeldA-8*elapsed);lastPeakAt=now;renderPeakMarkers({full:peakHeldFull,a:peakHeldA});if(!lastNumericAt||now-lastNumericAt>=NUMERIC_UPDATE_MS){const cut=now-1000,numFull=powerMeanDb(recentFull.filter(x=>x.t>=cut).map(x=>x.db)),numA=powerMeanDb(recentA.filter(x=>x.t>=cut).map(x=>x.db));renderNumbers({full:numFull,a:numA});lastNumericAt=now;}if(mode==='holding'){holdSamples.push(ar);status.textContent=`MEASURING VOICE · ${((now-holdStarted)/1000).toFixed(1)} s · raw A ${ar.toFixed(1)} dBFS · pre-voice background ${holdBackgroundRaw.toFixed(1)} dBFS`;}else if(mode==='live')status.textContent=`Live room meter · offset ${calibrationOffset>=0?'+':''}${calibrationOffset.toFixed(1)} dB`;else if(mode==='live-relative')status.textContent=`Live raw microphone level · A ${ar.toFixed(1)} dBFS`;setTechnicalDetails(ar);}
 function setControlsEnabled(enabled){for(const b of[c05,c025,manual,...presets])b.disabled=!enabled;spl.disabled=!enabled;}
 function stop(){if(timer)clearInterval(timer);timer=null;for(const n of[source,fullAnalyser,aAnalyser,silentSink])try{n?.disconnect();}catch{}stream?.getTracks().forEach(t=>t.stop());stream=source=fullAnalyser=aAnalyser=silentSink=null;recentA=[];recentFull=[];recentFullPeak=[];recentAPeak=[];smoothFull=smoothA=peakHeldFull=peakHeldA=null;lastPeakAt=0;lastNumericAt=0;holdBackgroundRaw=null;mode='idle';startButton.disabled=false;stopButton.disabled=true;setControlsEnabled(false);startButton.textContent='Start room meter';indicator.textContent='VOICE REFERENCE IDLE';Object.assign(indicator.style,{padding:'6px 10px',fontWeight:'700',fontSize:'13px',textAlign:'left',background:'rgba(120,120,120,.18)'});status.textContent=calibrationOffset===null?'Microphone off.':'Microphone off · calibration shown above will be reused next start.';}
 async function start(){if(!window.isSecureContext||!navigator.mediaDevices?.getUserMedia){status.textContent='Microphone unavailable — use HTTPS or localhost.';return;}startButton.disabled=true;startButton.textContent='Requesting microphone…';try{stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:false,noiseSuppression:false,autoGainControl:false}});const track=stream.getAudioTracks()[0],settings=track?.getSettings?.()||{};trackSettingsText=` · AGC ${onOff(settings.autoGainControl)} · NS ${onOff(settings.noiseSuppression)} · EC ${onOff(settings.echoCancellation)}`;const ctx=getAudioContext();if(ctx.state!=='running')await ctx.resume();source=ctx.createMediaStreamSource(stream);fullAnalyser=ctx.createAnalyser();fullAnalyser.fftSize=2048;fullAnalyser.smoothingTimeConstant=0;const hp1=ctx.createBiquadFilter(),hp2=ctx.createBiquadFilter(),shelf=ctx.createBiquadFilter(),lp=ctx.createBiquadFilter();hp1.type='highpass';hp1.frequency.value=110;hp1.Q.value=.707;hp2.type='highpass';hp2.frequency.value=160;hp2.Q.value=.707;shelf.type='highshelf';shelf.frequency.value=2500;shelf.gain.value=3;lp.type='lowpass';lp.frequency.value=9000;lp.Q.value=.707;aAnalyser=ctx.createAnalyser();aAnalyser.fftSize=2048;aAnalyser.smoothingTimeConstant=0;silentSink=ctx.createGain();silentSink.gain.value=0;source.connect(fullAnalyser);fullAnalyser.connect(silentSink);source.connect(hp1);hp1.connect(hp2);hp2.connect(shelf);shelf.connect(lp);lp.connect(aAnalyser);aAnalyser.connect(silentSink);silentSink.connect(ctx.destination);recentA=[];recentFull=[];recentFullPeak=[];recentAPeak=[];smoothFull=smoothA=peakHeldFull=peakHeldA=null;lastPeakAt=0;lastNumericAt=0;mode=calibrationOffset===null?'live-relative':'live';startButton.textContent='Room meter running';stopButton.disabled=false;setControlsEnabled(true);tick();timer=setInterval(tick,UPDATE_MS);}catch(error){stop();status.textContent=error?.name==='NotAllowedError'?'Microphone permission was not granted.':`Microphone could not start: ${error?.message||'unknown error'}`;}}
 startButton.addEventListener('click',start);stopButton.addEventListener('click',stop);for(const [b,t,d]of[[c05,63,'0.5 m'],[c025,69,'0.25 m']]){b.addEventListener('pointerdown',e=>beginHold(t,d,e));b.addEventListener('pointerup',endHold);b.addEventListener('pointercancel',endHold);b.addEventListener('pointerleave',e=>{if(mode==='holding'&&e.buttons===0)endHold(e);});}manual.addEventListener('click',setExternal);activeInstance={stop};return activeInstance;
}
function bootstrapRoomMeter(){if(!activeInstance&&document.getElementById('roomMeterPanel'))createRoomMeter();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bootstrapRoomMeter,{once:true});else bootstrapRoomMeter();